### ISSUE TITLE
Abbreviations not expanded when file is open in new window

### ISSUE THREAD

**Issue by jonocarroll** [WoodenMaiden/obsidian-abbreviations#71]
Many thanks for this plugin, I find it very useful for expanding shortcodes for callouts, e.g. `!note ` to produce `>[!note] `. 

This may be a limitation of how Obsidian works, but I noticed that if I open a file in a new window rather than the main window, abbreviations are not expanded when typed.

I'm currently using v1.0.1 of Abbreviations expander on Obsidian version: v1.5.12 on an M1 Mac (Darwin Kernel Version 23.2.0) running Sonoma (14.2.1).

**Comment by WoodenMaiden** [comment]
Hi there thank you for the feedback!

I made the input processing with [DOM Events](https://github.com/WoodenMaiden/obsidian-abbreviations/blob/5ef84f8e1a05402d41a9feec6e076bcb73cba1af/src/main.ts#L82), which seems to cause this issue as well as #61 and #62, I think this is what the Obsidian plugins docs advised to do back In the day.

**Comment by jonocarroll** [comment]
Thank you! I can confirm that update has resolved the issue and abbreviations are now expanded when the file is open in a new window.
